# WARNING: this file is not suitable for production, please use with caution
version: "3"

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5431:5432

  pgbouncer:
    image: pgbouncer/pgbouncer:1.12.0
    restart: unless-stopped
    environment:
      DATABASES_HOST: ${SQL_HOST}
      DATABASES_PASSWORD: ${SQL_PASSWORD}
      DATABASES_PORT: ${SQL_PORT}
      DATABASES_USER: ${SQL_USER}
      PGBOUNCER_LISTEN_PORT: 5432
  web:
    image: api
    build: .
    command: gunicorn -b 0.0.0.0:5000 api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/api.db
    volumes:
      - ./api:/code/api
      - ./db/:/db/
    ports:
      - "5000:5000"

volumes:
  postgres_data:
