# WARNING: this file is not suitable for production, please use with caution
version: "3"

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.flaskenv
    ports:
      - 5431:5432

#  pgbouncer:
#    image: pgbouncer/pgbouncer:1.12.0
#    restart: unless-stopped
#    env_file:
#      - ./.flaskenv
#    environment:
#      DATABASES_HOST: ${SQL_HOST}
#      DATABASES_PASSWORD: ${SQL_PASSWORD}
#      DATABASES_PORT: ${SQL_PORT}
#      DATABASES_USER: ${SQL_USER}
#      PGBOUNCER_LISTEN_PORT: 5432

  web:
    image: resolver
    build: .
    restart: unless-stopped
    command: gunicorn -b 0.0.0.0:5000 resolver.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/resolver
    volumes:
      - ./resolver:/code/resolver
      - ./db/:/db/
    ports:
     # need to make this a .env variable
      - "5001:5000"

volumes:
  postgres_data:
