version: "3"

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_PORT}:5432"

  web:
    image: resolver
    build: .
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./resolver:/code/resolver
      - ./migrations:/code/migrations
    ports:
        - "${RESOLVER_PORT}:5000"

volumes:
  postgres_data:
