"""empty message

Revision ID: 77dc2932d54d
Revises: 3c403aee5d08
Create Date: 2020-10-12 05:54:01.216372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "77dc2932d54d"
down_revision = "3c403aee5d08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "substances",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column(
            "identifiers", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("substances")
    # ### end Alembic commands ###
